### ISSUE TITLE
Running node recommender not working on Umbrel?

### ISSUE THREAD

**Issue by Unsettledroell** [ajpwahqgbi/lightning-tools#7]
I am trying to use node recommender on Umbrel, but get the following issue. I replaced  lightning-cli listnodes with  docker exec lnd lncli listnodes, as below. I created the file lnchannels.20210202 as in the readme. What am I doing wrong?

**(echo "{"; docker exec lnd lncli listnodes | tail -n +2 | head -n -2; echo "],"; cat lnchannels.20210202 | tail -n +2) | ./node_recommender.py <mypubkey> 2033 250**

No help topic for 'listnodes'
Traceback (most recent call last):
  File "./node_recommender.py", line 291, in <module>
    json_data = json.load(sys.stdin)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)

**Comment by Unsettledroell** [comment]
Okay, I get it it. The command listnodes does not seem to exist for LND, and as such, I guess this script needs to be adapted to work with LND properly.

**Comment by ajpwahqgbi** [comment]
As you discovered, there seems to be no LND equivalent to the C-Lightning `listnodes` command. However, this information is only used by the script to refer to nodes by their human-readable aliases. You can use this tool with LND, but it will print raw node IDs instead. 

For LND, just pipe the JSON result from `lncli describegraph` directly into `./node_recommender.py` instead of that subshell (everything in parentheses) intended for use with C-Lightning.
